//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCCXSoapService
{
    using SgkViziteReference;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="globalResponse", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UCCXSoapService.MissedCallList))]
    public partial class globalResponse : object
    {
        
        private bool statusField;
        
        private int statusCodeField;
        
        private string statusMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string statusMessage
        {
            get
            {
                return this.statusMessageField;
            }
            set
            {
                this.statusMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MissedCallList", Namespace="http://tempuri.org/")]
    public partial class MissedCallList : UCCXSoapService.globalResponse
    {
        
        private long countField;
        
        private System.Collections.Generic.List<UCCXSoapService.PhoneItemList> callsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.Generic.List<UCCXSoapService.PhoneItemList> calls
        {
            get
            {
                return this.callsField;
            }
            set
            {
                this.callsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneItemList", Namespace="http://tempuri.org/")]
    public partial class PhoneItemList : object
    {
        
        private long contactidField;
        
        private long agentidField;
        
        private long calltypeField;
        
        private string phonenumberField;
        
        private int dispositionField;
        
        private string csqnameField;
        
        private long startdatetimeEpochField;
        
        private long enddatetimeEpochField;
        
        private System.DateTime startdatetimeField;
        
        private System.DateTime enddatetimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long contactid
        {
            get
            {
                return this.contactidField;
            }
            set
            {
                this.contactidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long agentid
        {
            get
            {
                return this.agentidField;
            }
            set
            {
                this.agentidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long calltype
        {
            get
            {
                return this.calltypeField;
            }
            set
            {
                this.calltypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string phonenumber
        {
            get
            {
                return this.phonenumberField;
            }
            set
            {
                this.phonenumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int disposition
        {
            get
            {
                return this.dispositionField;
            }
            set
            {
                this.dispositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string csqname
        {
            get
            {
                return this.csqnameField;
            }
            set
            {
                this.csqnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long startdatetimeEpoch
        {
            get
            {
                return this.startdatetimeEpochField;
            }
            set
            {
                this.startdatetimeEpochField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long enddatetimeEpoch
        {
            get
            {
                return this.enddatetimeEpochField;
            }
            set
            {
                this.enddatetimeEpochField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime startdatetime
        {
            get
            {
                return this.startdatetimeField;
            }
            set
            {
                this.startdatetimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime enddatetime
        {
            get
            {
                return this.enddatetimeField;
            }
            set
            {
                this.enddatetimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UCCXSoapService.uccxSoap")]
    public interface uccxSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MissedCallListService", ReplyAction="*")]
        System.Threading.Tasks.Task<UCCXSoapService.MissedCallListServiceResponse> MissedCallListServiceAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MissedCallListServiceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MissedCallListService", Namespace="http://tempuri.org/", Order=0)]
        public UCCXSoapService.MissedCallListServiceRequestBody Body;
        
        public MissedCallListServiceRequest()
        {
        }
        
        public MissedCallListServiceRequest(UCCXSoapService.MissedCallListServiceRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MissedCallListServiceRequestBody
    {
        
        public MissedCallListServiceRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MissedCallListServiceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MissedCallListServiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public UCCXSoapService.MissedCallListServiceResponseBody Body;
        
        public MissedCallListServiceResponse()
        {
        }
        
        public MissedCallListServiceResponse(UCCXSoapService.MissedCallListServiceResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MissedCallListServiceResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UCCXSoapService.MissedCallList MissedCallListServiceResult;
        
        public MissedCallListServiceResponseBody()
        {
        }
        
        public MissedCallListServiceResponseBody(UCCXSoapService.MissedCallList MissedCallListServiceResult)
        {
            this.MissedCallListServiceResult = MissedCallListServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface uccxSoapChannel : UCCXSoapService.uccxSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class uccxSoapClient : System.ServiceModel.ClientBase<UCCXSoapService.uccxSoap>, UCCXSoapService.uccxSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public uccxSoapClient() :
               base(uccxSoapClient.GetDefaultBinding(), uccxSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.uccxSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }


        public uccxSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(uccxSoapClient.GetBindingForEndpoint(endpointConfiguration), uccxSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public uccxSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(uccxSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public uccxSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(uccxSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public uccxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<UCCXSoapService.MissedCallListServiceResponse> MissedCallListServiceAsync()
        {
            return base.Channel.MissedCallListServiceAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.uccxSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.uccxSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.uccxSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.110.100:9090/uccx.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.uccxSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.110.100:9090/uccx.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }


        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return uccxSoapClient.GetBindingForEndpoint(EndpointConfiguration.uccxSoap);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return uccxSoapClient.GetEndpointAddress(EndpointConfiguration.uccxSoap);
        }


        public enum EndpointConfiguration
        {
            
            uccxSoap,
            
            uccxSoap12,
        }
    }
}
